### ISSUE TITLE
LaTeXing 1.2.5 unable to compile Rnw script

### ISSUE THREAD

**Issue by smithdanielle** [LaTeXing/LaTeXing#102]
Using [this minimal example](https://github.com/yihui/knitr-examples/blob/master/002-minimal.Rnw), LaTeXing is unable to compile a `.Rnw` file, reporting:

```
COULD NOT COMPILE! "Rscript -e "library(knitr); knit('test-rnw.Rnw')""
```

The sample document compiles with no errors using RStudio. LaTeXing is able to compile a `.tex` file with no issues.

A system check reveals no problems (though I am a little perplexed that `sublime` is missing):

```
+------------+----------+---------+---------------------------+
| Executable | Type     | Status  | Path                      |
+------------+----------+---------+---------------------------+
| perl       | required | Found   | perl                      |
| latexmk    | required | Found   | latexmk                   |
| texcount   | optional | Found   | texcount                  |
| biber      | optional | Found   | biber                     |
| bibtex     | optional | Found   | bibtex                    |
| pdflatex   | optional | Found   | pdflatex                  |
| xelatex    | optional | Found   | xelatex                   |
| lualatex   | optional | Found   | lualatex                  |
| kpsewhich  | optional | Found   | kpsewhich                 |
| texdoc     | optional | Found   | texdoc                    |
| sublime    | optional | Missing |                           |
| rscript    | optional | Found   | Rscript                   |
| preview    | viewer   | Found   | /Applications/Preview.app |
| skim       | viewer   | Found   | /Applications/Skim.app    |
+------------+----------+---------+---------------------------+

+----------------+
| Searched Path  |
+----------------+
| /sbin          |
| /usr/local/bin |
| /opt/local/bin |
| /usr/sbin      |
| /usr/texbin    |
| /usr/bin       |
| /bin           |
+----------------+
** Checked with LaTeXing 1.2.5
```

Dump of `R`'s `sessionInfo()` can be found [here](https://gist.githubusercontent.com/smithdanielle/62cc822ace5e9f4e408a/raw/38aadbac99ad702ea83a8b13a1a31733d3d60bf2/sessionInfoDump.txt).

**Comment by rundel** [comment]
Just updated to LaTeXing 1.2.5 and I am seeing the same issue on OS X (10.10.2) - system check also runs cleanly for me.

**Comment by jtappler** [comment]
I'm getting the same error msgs since last night. Knitr support was broken, could not compile `.Rnw` and `.Rtex` files. 
```
COULD NOT COMPILE! "Rscript -e "library(knitr); knit('ThHypothermia.Rnw')""
```
with popup warning `Could not move the pdf or synctex file. Close the pdf viewer to reset the file access or other permission problems.`

LaTeXing 1.2.5
OS X v10.10.2/v10.10.3 beta 3
R version 3.1.2 with knitr 1.9

**Comment by csch0** [comment]
I think its related to #101. Still very odd since I changed nothing there, just worked on #94 but will be fixed asap. Working on it.

**Comment by csch0** [comment]
Ok fixed this first, pushing 1.2.6 later tonight. Should be fixed!

**Comment by csch0** [comment]
Should be fixed in 1.2.6, please let me know.

**Comment by jtappler** [comment]
Just updated, it appears to be working again after reboot.

**Comment by rundel** [comment]
1.2.6 is working for me as well.

**Comment by jtappler** [comment]
It works fine for most files. 
However I found out that for some larger ones (> 10KB), it still throw the same error during the midway of compiling. 
Attached one sample `.Rnw` file for your testing: http://cl.ly/ZxTg

**Comment by csch0** [comment]
Thanks for the file @jtappler, check this later.

**Comment by smithdanielle** [comment]
Can confirm that 1.2.6 works fine after reboot. Thanks for quick fix!

**Comment by rhydar** [comment]
Hi. I am having similar errors with 1.2.9. Recently updated. The Rnw file compiles in RStudio.
